name: PR Checks

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.ts'
      - '**.js'
      - '**.json'
      - '.github/workflows/**'
      - 'pnpm-lock.yaml'

jobs:
  check-changeset:
    name: Verify Changeset
    runs-on: ubuntu-latest
    outputs:
      has-changeset: ${{ steps.check.outputs.has-changeset }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 22

      - name: Check for changeset
        id: check
        run: |
          # Check if this PR touches any code files
          git diff --name-only origin/${{ github.base_ref }}...HEAD | grep -E '\.(ts|js|json)$' > /dev/null || {
            echo "No code changes detected, skipping changeset check"
            echo "has-changeset=skip" >> $GITHUB_OUTPUT
            exit 0
          }
          
          # Check if there's a changeset
          if pnpm changeset status --since=origin/${{ github.base_ref }}; then
            echo "has-changeset=true" >> $GITHUB_OUTPUT
          else
            echo "::error::This PR contains code changes but is missing a changeset. Please run 'pnpm changeset' and commit the generated file."
            echo "::error::If this change doesn't need a version bump (e.g., internal refactoring, tests, docs), you can create an empty changeset."
            echo "has-changeset=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  lint-and-test:
    name: Lint, Type Check & Test
    runs-on: ubuntu-latest
    needs: check-changeset
    if: ${{ needs.check-changeset.outputs.has-changeset != 'false' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup-node-pnpm
        with:
          node-version: 22

      - name: Run Linter
        run: pnpm lint

      - name: Run Type Check
        run: pnpm typecheck

      - name: Build Project
        run: pnpm build

      - name: Run Tests with Coverage
        run: pnpm test:coverage

      - name: Upload Coverage Reports
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7